# Generated by Django 5.2.9 on 2025-12-26 11:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=15)),
                ('user_email', models.EmailField(max_length=25)),
                ('user_display_name', models.CharField(max_length=15)),
                ('user_contact', models.CharField(max_length=15)),
                ('user_city', models.CharField(max_length=15)),
                ('user_date_of_birth', models.DateField()),
                ('user_password', models.CharField(max_length=10)),
                ('user_image', models.ImageField(upload_to='image/profile_picture')),
                ('user_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
