# Generated by Django 5.2.9 on 2025-12-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
